import type { Metadata } from "next";
import "./globals.css";
import "@sopt-makers/ui/dist/index.css";
import { css } from "@/styled-system/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={css({
          ...rootLayoutStyle,
        })}
      >
        <div id="modal"></div>
        {children}
      </body>
    </html>
  );
}

const rootLayoutStyle = css.raw({
  backgroundColor: "background",
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  height: "100vh",
});
