/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LoginErrorIndexImport } from './routes/login-error/index'
import { Route as SocialAccountLinkingSocialIndexImport } from './routes/social-account-linking/social/index'
import { Route as SocialAccountLinkingAuthIndexImport } from './routes/social-account-linking/auth/index'
import { Route as SignUpSocialIndexImport } from './routes/sign-up/social/index'
import { Route as SignUpAuthIndexImport } from './routes/sign-up/auth/index'
import { Route as AuthGoogleCallbackIndexImport } from './routes/auth/google/callback/index'
import { Route as AuthAppleCallbackIndexImport } from './routes/auth/apple/callback/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginErrorIndexRoute = LoginErrorIndexImport.update({
  id: '/login-error/',
  path: '/login-error/',
  getParentRoute: () => rootRoute,
} as any)

const SocialAccountLinkingSocialIndexRoute =
  SocialAccountLinkingSocialIndexImport.update({
    id: '/social-account-linking/social/',
    path: '/social-account-linking/social/',
    getParentRoute: () => rootRoute,
  } as any)

const SocialAccountLinkingAuthIndexRoute =
  SocialAccountLinkingAuthIndexImport.update({
    id: '/social-account-linking/auth/',
    path: '/social-account-linking/auth/',
    getParentRoute: () => rootRoute,
  } as any)

const SignUpSocialIndexRoute = SignUpSocialIndexImport.update({
  id: '/sign-up/social/',
  path: '/sign-up/social/',
  getParentRoute: () => rootRoute,
} as any)

const SignUpAuthIndexRoute = SignUpAuthIndexImport.update({
  id: '/sign-up/auth/',
  path: '/sign-up/auth/',
  getParentRoute: () => rootRoute,
} as any)

const AuthGoogleCallbackIndexRoute = AuthGoogleCallbackIndexImport.update({
  id: '/auth/google/callback/',
  path: '/auth/google/callback/',
  getParentRoute: () => rootRoute,
} as any)

const AuthAppleCallbackIndexRoute = AuthAppleCallbackIndexImport.update({
  id: '/auth/apple/callback/',
  path: '/auth/apple/callback/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login-error/': {
      id: '/login-error/'
      path: '/login-error'
      fullPath: '/login-error'
      preLoaderRoute: typeof LoginErrorIndexImport
      parentRoute: typeof rootRoute
    }
    '/sign-up/auth/': {
      id: '/sign-up/auth/'
      path: '/sign-up/auth'
      fullPath: '/sign-up/auth'
      preLoaderRoute: typeof SignUpAuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/sign-up/social/': {
      id: '/sign-up/social/'
      path: '/sign-up/social'
      fullPath: '/sign-up/social'
      preLoaderRoute: typeof SignUpSocialIndexImport
      parentRoute: typeof rootRoute
    }
    '/social-account-linking/auth/': {
      id: '/social-account-linking/auth/'
      path: '/social-account-linking/auth'
      fullPath: '/social-account-linking/auth'
      preLoaderRoute: typeof SocialAccountLinkingAuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/social-account-linking/social/': {
      id: '/social-account-linking/social/'
      path: '/social-account-linking/social'
      fullPath: '/social-account-linking/social'
      preLoaderRoute: typeof SocialAccountLinkingSocialIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/apple/callback/': {
      id: '/auth/apple/callback/'
      path: '/auth/apple/callback'
      fullPath: '/auth/apple/callback'
      preLoaderRoute: typeof AuthAppleCallbackIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/google/callback/': {
      id: '/auth/google/callback/'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login-error': typeof LoginErrorIndexRoute
  '/sign-up/auth': typeof SignUpAuthIndexRoute
  '/sign-up/social': typeof SignUpSocialIndexRoute
  '/social-account-linking/auth': typeof SocialAccountLinkingAuthIndexRoute
  '/social-account-linking/social': typeof SocialAccountLinkingSocialIndexRoute
  '/auth/apple/callback': typeof AuthAppleCallbackIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login-error': typeof LoginErrorIndexRoute
  '/sign-up/auth': typeof SignUpAuthIndexRoute
  '/sign-up/social': typeof SignUpSocialIndexRoute
  '/social-account-linking/auth': typeof SocialAccountLinkingAuthIndexRoute
  '/social-account-linking/social': typeof SocialAccountLinkingSocialIndexRoute
  '/auth/apple/callback': typeof AuthAppleCallbackIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login-error/': typeof LoginErrorIndexRoute
  '/sign-up/auth/': typeof SignUpAuthIndexRoute
  '/sign-up/social/': typeof SignUpSocialIndexRoute
  '/social-account-linking/auth/': typeof SocialAccountLinkingAuthIndexRoute
  '/social-account-linking/social/': typeof SocialAccountLinkingSocialIndexRoute
  '/auth/apple/callback/': typeof AuthAppleCallbackIndexRoute
  '/auth/google/callback/': typeof AuthGoogleCallbackIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login-error'
    | '/sign-up/auth'
    | '/sign-up/social'
    | '/social-account-linking/auth'
    | '/social-account-linking/social'
    | '/auth/apple/callback'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login-error'
    | '/sign-up/auth'
    | '/sign-up/social'
    | '/social-account-linking/auth'
    | '/social-account-linking/social'
    | '/auth/apple/callback'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/login-error/'
    | '/sign-up/auth/'
    | '/sign-up/social/'
    | '/social-account-linking/auth/'
    | '/social-account-linking/social/'
    | '/auth/apple/callback/'
    | '/auth/google/callback/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginErrorIndexRoute: typeof LoginErrorIndexRoute
  SignUpAuthIndexRoute: typeof SignUpAuthIndexRoute
  SignUpSocialIndexRoute: typeof SignUpSocialIndexRoute
  SocialAccountLinkingAuthIndexRoute: typeof SocialAccountLinkingAuthIndexRoute
  SocialAccountLinkingSocialIndexRoute: typeof SocialAccountLinkingSocialIndexRoute
  AuthAppleCallbackIndexRoute: typeof AuthAppleCallbackIndexRoute
  AuthGoogleCallbackIndexRoute: typeof AuthGoogleCallbackIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginErrorIndexRoute: LoginErrorIndexRoute,
  SignUpAuthIndexRoute: SignUpAuthIndexRoute,
  SignUpSocialIndexRoute: SignUpSocialIndexRoute,
  SocialAccountLinkingAuthIndexRoute: SocialAccountLinkingAuthIndexRoute,
  SocialAccountLinkingSocialIndexRoute: SocialAccountLinkingSocialIndexRoute,
  AuthAppleCallbackIndexRoute: AuthAppleCallbackIndexRoute,
  AuthGoogleCallbackIndexRoute: AuthGoogleCallbackIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login-error/",
        "/sign-up/auth/",
        "/sign-up/social/",
        "/social-account-linking/auth/",
        "/social-account-linking/social/",
        "/auth/apple/callback/",
        "/auth/google/callback/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login-error/": {
      "filePath": "login-error/index.tsx"
    },
    "/sign-up/auth/": {
      "filePath": "sign-up/auth/index.tsx"
    },
    "/sign-up/social/": {
      "filePath": "sign-up/social/index.tsx"
    },
    "/social-account-linking/auth/": {
      "filePath": "social-account-linking/auth/index.tsx"
    },
    "/social-account-linking/social/": {
      "filePath": "social-account-linking/social/index.tsx"
    },
    "/auth/apple/callback/": {
      "filePath": "auth/apple/callback/index.tsx"
    },
    "/auth/google/callback/": {
      "filePath": "auth/google/callback/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
